#! /bin/sh

wmname LG3D

bspc config border_width        0
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 16
bspc config focus_follows_pointer	true

bspc monitor HDMI1 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX X

bspc monitor DVI-I-1 -n ""
bspc monitor DVI-D-0 -n ""

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

export PANEL_FIFO="/tmp/panel-fifo"
panel
